/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas_prakstrukdat;

import javax.swing.JOptionPane;

/**
 *
 * @author SUCI WULANDARI - 210605110154
 */
public class First extends javax.swing.JFrame {

    /**
     * Creates new form First
     */
    public First() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        stack = new javax.swing.JButton();
        queue = new javax.swing.JButton();
        sorting = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));
        jPanel1.setPreferredSize(new java.awt.Dimension(1010, 520));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray));
        jPanel2.setPreferredSize(new java.awt.Dimension(734, 437));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stack.setBackground(new java.awt.Color(255, 255, 255));
        stack.setFont(new java.awt.Font("HP Simplified Hans", 0, 14)); // NOI18N
        stack.setText("Stack");
        stack.setMaximumSize(new java.awt.Dimension(73, 27));
        stack.setMinimumSize(new java.awt.Dimension(73, 27));
        stack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stackMouseExited(evt);
            }
        });
        stack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stackActionPerformed(evt);
            }
        });
        jPanel2.add(stack, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 250, 52));

        queue.setBackground(new java.awt.Color(255, 255, 255));
        queue.setFont(new java.awt.Font("HP Simplified Hans", 0, 14)); // NOI18N
        queue.setText("Queue");
        queue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                queueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                queueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                queueMouseExited(evt);
            }
        });
        queue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queueActionPerformed(evt);
            }
        });
        jPanel2.add(queue, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 250, 49));

        sorting.setBackground(new java.awt.Color(255, 255, 255));
        sorting.setFont(new java.awt.Font("HP Simplified Hans", 0, 14)); // NOI18N
        sorting.setText("Sorting");
        sorting.setMaximumSize(new java.awt.Dimension(73, 27));
        sorting.setMinimumSize(new java.awt.Dimension(73, 27));
        sorting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sortingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sortingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sortingMouseExited(evt);
            }
        });
        sorting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortingActionPerformed(evt);
            }
        });
        jPanel2.add(sorting, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 250, 48));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 53)); // NOI18N
        jLabel1.setText("STRUKTUR  DATA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 500, 181));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 17, 962, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stackActionPerformed
        // TODO add your handling code here:
        new Stack().setVisible(true);
        this.setVisible(false);//menutup frame sebelumnya
    }//GEN-LAST:event_stackActionPerformed

    private void queueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queueActionPerformed
        // TODO add your handling code here:
        new Queue().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_queueActionPerformed

    private void sortingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortingActionPerformed
        // TODO add your handling code here:
        new Sorting().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_sortingActionPerformed

    private void stackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stackMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_stackMouseClicked

    private void stackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stackMouseEntered
        // TODO add your handling code here
    }//GEN-LAST:event_stackMouseEntered

    private void queueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_queueMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_queueMouseClicked

    private void sortingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sortingMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sortingMouseClicked

    private void queueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_queueMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_queueMouseEntered

    private void queueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_queueMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_queueMouseExited

    private void sortingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sortingMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_sortingMouseEntered

    private void sortingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sortingMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_sortingMouseExited

    private void stackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stackMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_stackMouseExited
    public void doexit() {
        int confirm = JOptionPane.showConfirmDialog(null,
                "Apa Anda Akan Keluar?", "Tutup Aplikasi",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0); //untuk menutup atau keluar dari program.
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new First().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton queue;
    private javax.swing.JButton sorting;
    private javax.swing.JButton stack;
    // End of variables declaration//GEN-END:variables
}
