/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas_prakstrukdat;

import java.util.Arrays;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;

/**
 *
 * @author SUCI WULANDARI - 210605110154
 */
public class Queue extends javax.swing.JFrame {

    algQueue theQue; // menghubungkand dengan kelas algQueue

    public Queue() {
        initComponents();
        inputX.setText("");
        varx.setText("");
        vary.setText("");
        var1.setText("");
        var2.setText("");
        var3.setText("");
        var3.setText("");
        var4.setText("");
        var5.setText("");
        var6.setText("");
        var7.setText("");
        var8.setText("");
        notes.setVisible(false);

        head2.setVisible(false);
        head3.setVisible(false);
        head1.setVisible(false);
        tail1.setVisible(false);
        tail2.setVisible(false);
        tail4.setVisible(false);
        tail3.setVisible(false);

        theQue = new algQueue(4);

        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        inputX = new javax.swing.JTextField();
        dequeue = new javax.swing.JPanel();
        TF2 = new javax.swing.JLabel();
        enqueue = new javax.swing.JPanel();
        TF1 = new javax.swing.JLabel();
        var1 = new javax.swing.JTextField();
        var2 = new javax.swing.JTextField();
        var3 = new javax.swing.JTextField();
        var4 = new javax.swing.JTextField();
        var5 = new javax.swing.JTextField();
        var6 = new javax.swing.JTextField();
        var7 = new javax.swing.JTextField();
        var8 = new javax.swing.JTextField();
        varx = new javax.swing.JTextField();
        vary = new javax.swing.JTextField();
        notes = new javax.swing.JLabel();
        head1 = new javax.swing.JLabel();
        tail1 = new javax.swing.JLabel();
        head2 = new javax.swing.JLabel();
        head3 = new javax.swing.JLabel();
        tail4 = new javax.swing.JLabel();
        tail3 = new javax.swing.JLabel();
        tail2 = new javax.swing.JLabel();
        jlStack = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMinimumSize(new java.awt.Dimension(1010, 520));
        jPanel1.setPreferredSize(new java.awt.Dimension(1010, 520));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 60)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Queue");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 220, 80));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, 20, 240));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, 20, 240));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 80, 10));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 80, 20));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 80, 20));

        inputX.setBackground(new java.awt.Color(0, 102, 102));
        inputX.setFont(new java.awt.Font("HP Simplified Hans", 0, 18)); // NOI18N
        inputX.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputX.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.add(inputX, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 150, 70));

        dequeue.setPreferredSize(new java.awt.Dimension(150, 40));
        dequeue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dequeueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dequeueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dequeueMouseExited(evt);
            }
        });
        dequeue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TF2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TF2.setText("Dequeue");
        dequeue.add(TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, 30));

        jPanel2.add(dequeue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 260, 50));

        enqueue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enqueueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enqueueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enqueueMouseExited(evt);
            }
        });
        enqueue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TF1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TF1.setText("Enqueue");
        enqueue.add(TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 80, 30));

        jPanel2.add(enqueue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 260, 50));

        var1.setBackground(new java.awt.Color(0, 102, 102));
        var1.setFont(new java.awt.Font("HP Simplified Hans", 0, 16)); // NOI18N
        var1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        var1.setText("var 1");
        var1.setBorder(null);
        var1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var1ActionPerformed(evt);
            }
        });
        jPanel2.add(var1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 70, 50));

        var2.setBackground(new java.awt.Color(0, 102, 102));
        var2.setFont(new java.awt.Font("HP Simplified Hans", 0, 16)); // NOI18N
        var2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        var2.setText("var 2");
        var2.setBorder(null);
        var2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var2ActionPerformed(evt);
            }
        });
        jPanel2.add(var2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 60, 50));

        var3.setBackground(new java.awt.Color(0, 102, 102));
        var3.setFont(new java.awt.Font("HP Simplified Hans", 0, 16)); // NOI18N
        var3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        var3.setText("var 3");
        var3.setBorder(null);
        var3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var3ActionPerformed(evt);
            }
        });
        jPanel2.add(var3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, 60, 50));

        var4.setBackground(new java.awt.Color(0, 102, 102));
        var4.setFont(new java.awt.Font("HP Simplified Hans", 0, 16)); // NOI18N
        var4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        var4.setText("var 4");
        var4.setBorder(null);
        jPanel2.add(var4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, 80, 40));

        var5.setBackground(new java.awt.Color(0, 102, 102));
        var5.setFont(new java.awt.Font("HP Simplified Hans", 0, 16)); // NOI18N
        var5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        var5.setText("var 5");
        var5.setBorder(null);
        var5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var5ActionPerformed(evt);
            }
        });
        jPanel2.add(var5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 330, 70, 40));

        var6.setBackground(new java.awt.Color(0, 102, 102));
        var6.setFont(new java.awt.Font("HP Simplified Hans", 0, 16)); // NOI18N
        var6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        var6.setText("var 6");
        var6.setBorder(null);
        var6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var6ActionPerformed(evt);
            }
        });
        jPanel2.add(var6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, 70, 40));

        var7.setBackground(new java.awt.Color(0, 102, 102));
        var7.setFont(new java.awt.Font("HP Simplified Hans", 0, 16)); // NOI18N
        var7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        var7.setText("var 7");
        var7.setBorder(null);
        var7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var7ActionPerformed(evt);
            }
        });
        jPanel2.add(var7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 70, 40));

        var8.setBackground(new java.awt.Color(0, 102, 102));
        var8.setFont(new java.awt.Font("HP Simplified Hans", 0, 16)); // NOI18N
        var8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        var8.setText("var 8");
        var8.setBorder(null);
        var8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var8ActionPerformed(evt);
            }
        });
        jPanel2.add(var8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 70, 40));

        varx.setBackground(new java.awt.Color(0, 102, 102));
        varx.setFont(new java.awt.Font("HP Simplified Hans", 0, 16)); // NOI18N
        varx.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        varx.setText("varx");
        varx.setBorder(null);
        varx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varxActionPerformed(evt);
            }
        });
        jPanel2.add(varx, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 70, 50));

        vary.setBackground(new java.awt.Color(0, 102, 102));
        vary.setFont(new java.awt.Font("HP Simplified Hans", 0, 16)); // NOI18N
        vary.setText("var y");
        vary.setBorder(null);
        jPanel2.add(vary, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 90, 60, 50));

        notes.setFont(new java.awt.Font("HP Simplified Hans", 0, 16)); // NOI18N
        notes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        notes.setText("Full");
        jPanel2.add(notes, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 160, 50, 40));

        head1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        head1.setText("Head");
        jPanel2.add(head1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 350, 60, 30));

        tail1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tail1.setText("Tail");
        jPanel2.add(tail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, 60, 30));

        head2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        head2.setText("Head");
        jPanel2.add(head2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 280, 60, 30));

        head3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        head3.setText("Head");
        jPanel2.add(head3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 220, 60, 30));

        tail4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tail4.setText("Tail");
        jPanel2.add(tail4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 60, 30));

        tail3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tail3.setText("Tail");
        jPanel2.add(tail3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 60, 30));

        tail2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tail2.setText("Tail");
        jPanel2.add(tail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, 60, 30));

        jlStack.setFont(new java.awt.Font("HP Simplified Hans", 0, 14)); // NOI18N
        jlStack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlStack.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Progress", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.add(jlStack, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 260, 320));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 950, 460));

        back.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("<");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 60, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void var1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_var1ActionPerformed

    private void var2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_var2ActionPerformed

    private void var3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_var3ActionPerformed

    private void var6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_var6ActionPerformed

    private void var7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_var7ActionPerformed

    private void var8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_var8ActionPerformed

    private void varxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varxActionPerformed
    public void doexit() {
        int confirm = JOptionPane.showConfirmDialog(null,
                "Apa Anda Akan Keluar?", "Tutup Aplikasi",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);  //untuk keluar dari program.

        }
    }

    private void enqueueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enqueueMouseClicked
        // TODO add your handling code here:

        String data = inputX.getText();
        theQue.insert(inputX.getText());
        jlStack.setText(Arrays.toString(theQue.queArray));

        if (data.equals("")) {
            JOptionPane.showMessageDialog(null, "Masukan data!");

        } else {
            Thread th = new Thread() { // ini kelas pd java untuk mengset waktu eksekusi
                @Override

                public void run() {
                    try {
                        for (int a = 0; a <= 10; a++) {
                            Thread.sleep(500); // Set Waktu pending selama 5 milidetik
                            if (a == 1) {
                                run1();
                            }
                            if (a == 2) {
                                run2();
                            }
                            if (a == 3) {
                                run3();
                            }
                            if (a == 4) {
                                run4();
                            }
                            if (a == 5) {
                                run5();
                            }
                            if (a == 6) {
                                run6();
                            }
                            if (a == 7) {
                                checkHead();
                                checkTail();
                            }
                        }
                    } catch (Exception ex) {
                        System.out.println(ex);
                    }
                }
            };
            th.start();

        }
    }//GEN-LAST:event_enqueueMouseClicked

    private void enqueueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enqueueMouseEntered
        // TODO add your handling code here:
        x1();
    }//GEN-LAST:event_enqueueMouseEntered
    public void x1() {
        setColor(enqueue);
        setColorTF(TF1);
        setBorder2(enqueue);
    }

    private void enqueueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enqueueMouseExited
        // TODO add your handling code here:
        y1();
    }//GEN-LAST:event_enqueueMouseExited
    public void y1() {
        resetColor(enqueue);
        resetColorTF(TF1);
    }

    private void dequeueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dequeueMouseEntered
        // TODO add your handling code here:
        x2();
    }//GEN-LAST:event_dequeueMouseEntered
    public void x2() {
        setBorder2(dequeue);
        setColor(dequeue);
        setColorTF(TF2);
    }
    private void dequeueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dequeueMouseExited
        // TODO add your handling code here:
        y2();
    }//GEN-LAST:event_dequeueMouseExited
    public void y2() {
        resetColorTF(TF2);
        resetColor(dequeue);
    }


    private void dequeueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dequeueMouseClicked
        // TODO add your handling code here:
        run7();
        theQue.remove();
        jlStack.setText(Arrays.toString(theQue.queArray));
    }//GEN-LAST:event_dequeueMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        new First().setVisible(true); // kembali ke frame First
        this.setVisible(false); // untuk menutup page/frame sebelumnyaa
    }//GEN-LAST:event_backMouseClicked

    private void var5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_var5ActionPerformed

    private void run1() { // variabel jalan dr paling kiri atas 
        String data = varx.getText();
        String input = inputX.getText();

        if (data.equals("")) { // equals itu method pembanding string pada java

            varx.setText(input);
        }

    }

    private void run2() { // variabel input jalan ke sampingnya
        String data = var1.getText();
        String input = varx.getText();

        if (data.equals("")) {// ketika data yang dibandingkan(VAR1) kosong, maka data tersebut akan diisi

            var1.setText(input);
            varx.setText("");
        }

    }

    private void run3() { // variabel jalan lagi
        String data = var2.getText();
        String a1 = var1.getText();

        if (data.equals("")) { // ketika data yang dibandingkan(VAR2) kosong, maka data tersebut akan diisi
            var2.setText(a1);
            var1.setText("");
            notes.setVisible(false);
            vary.setText("");
        } else { // ketika data yang mau dibandingkan (pads Var 2 itu sudah terisi) maka akan masuk ke VarY dan notes(full) bernilai true
            vary.setText(a1);
            var1.setText("");
            notes.setVisible(true);
        }
    }

    private void run4() {
        String data = var3.getText();
        String a12 = var2.getText();

        if (data.equals("")) { // ketika data yang dibandingkan(VAR3) kosong, maka data tersebut akan diisi
            var3.setText(a12);
            var2.setText("");
        }
    }

    private void run5() {
        String data = var4.getText();
        String a13 = var3.getText();

        if (data.equals("")) {// ketika data yang dibandingkan(VAR4) kosong, maka data tersebut akan diisi
            var4.setText(a13);
            var3.setText("");
        }
    }

    private void run6() {
        String data = var5.getText();
        String a14 = var4.getText();

        if (data.equals("")) {// ketika data yang dibandingkan(VAR5) kosong, maka data tersebut akan diisi
            var5.setText(a14);
            var4.setText("");
        }
    }

    private void run7x() {
        String d = var2.getText();
        String e = var3.getText();
        String f = var4.getText();
        String g = var5.getText();

        if (d.equals("") && e.equals("") && f.equals("") && g.equals("")) {

            //head
            head1.setVisible(false);

            head3.setVisible(false);

            head2.setVisible(false);

            //tail
            tail1.setVisible(false);

            tail3.setVisible(false);

            tail2.setVisible(false);

            tail4.setVisible(false);

            JOptionPane.showMessageDialog(null, "Data sudah dihapus");

        } else {
            Thread th = new Thread() {
                @Override
                public void run() {
                    try {
                        for (int a = 0; a <= 7; a++) {
                            Thread.sleep(800);
                            if (a == 1) {
                                run7a();
                            }
                            if (a == 2) {
                                run7b();
                                checkHead();
                            }
                            if (a == 3) {
                                run7c();
                            }
                            if (a == 4) {
                                run7d();
                            }
                            if (a == 5) {
                                checkMD2();
                            }
                        }
                    } catch (Exception ex) {
                        System.out.println(ex);
                    }
                }
            };
            th.start();
        }
    }

    public void checkMD2() {
        Thread th = new Thread() {
            @Override
            public void run() {
                try {
                    for (int a = 0; a <= 10; a++) {
                        Thread.sleep(500);
                        if (a == 1) {
                            runMD1();
                        }
                        if (a == 2) {
                            runMD2();
                        }
                        if (a == 3) {
                            runMD3();
                        }
                        if (a == 4) {
                            runMD4();
                        }
                        if (a == 5) {
                            checkHead();
                            checkTail();
                        }
                        if (a == 6) {
                            run7x();
                        }
                    }
                } catch (Exception ex) {
                    System.out.println(ex);
                }
            }
        };
        th.start();

    }

    public void checkHead() {

        String d = var2.getText(); // variabel Di Paling Atas
        String e = var3.getText();
        String f = var4.getText();
        String g = var5.getText();
        String h = var6.getText(); // variabel mulai keluar

        //yang kedua
        if (f.equals("") && !(e.equals(""))) { // var4 kosong, && var3 terisi

            head3.setVisible(true);

            head1.setVisible(false);

            head2.setVisible(false);

        } else if (g.equals("") && !(f.equals(""))) { // var5 kosong, && var4 terisi

            head2.setVisible(true);

            head3.setVisible(false);

            head1.setVisible(false);

        } else if (h.equals("") && !(g.equals(""))) { // var6 kosong, && var5 terisi

            head1.setVisible(true);

            head3.setVisible(false);

            head2.setVisible(false);
        }

    }

    public void checkTail() {

        String c = var1.getText();
        String d = var2.getText();
        String e = var3.getText();
        String f = var4.getText();
        String g = var5.getText();
        String h = var6.getText();

        if (f.equals("") && !(g.equals(""))) { //var4 Kosong, Var5 terisi

            tail1.setVisible(true);

            tail3.setVisible(false);

            tail2.setVisible(false);

            tail4.setVisible(false);

        } else if (e.equals("") && !(f.equals(""))) { //var3 Kosong, Var4 terisi
            tail2.setVisible(true);

            tail3.setVisible(false);

            tail1.setVisible(false);

            tail4.setVisible(false);

        } else if (d.equals("") && !(e.equals(""))) { // Var2 Kosong, Var3 terisi

            tail3.setVisible(true);

            tail1.setVisible(false);

            tail2.setVisible(false);

            tail4.setVisible(false);

        } else if (c.equals("") && !(d.equals(""))) { // Var1 Kosong, Var2 terisi
            tail4.setVisible(true);

            tail3.setVisible(false);

            tail1.setVisible(false);

            tail2.setVisible(false);

        }
    }

    public void checkMD1() {
        Thread th = new Thread() {
            @Override
            public void run() {
                try {
                    for (int a = 0; a <= 10; a++) {
                        Thread.sleep(500);
                        if (a == 1) {
                            runMD1();
                        }
                        if (a == 2) {
                            runMD2();
                        }
                        if (a == 3) {
                            runMD3();
                        }
                        if (a == 4) {
                            runMD4();
                        }
                        if (a == 5) {
                            checkHead();
                            checkTail();
                        }
                    }
                } catch (Exception ex) {
                    System.out.println(ex);
                }
            }
        };
        th.start();

    }

    private void runMD1() {
        String v4 = var4.getText();
        String v5 = var5.getText();
        if (v5.equals("") && !(v4.equals(""))) {
            var5.setText(v4);
            var4.setText("");
        }
    }

    private void runMD2() {
        String v3 = var3.getText();
        String v4 = var4.getText();
        if (v4.equals("") && !(v3.equals(""))) {
            var4.setText(v3);
            var3.setText("");
        }
    }

    private void runMD3() {
        String v2 = var2.getText();
        String v3 = var3.getText();
        if (v3.equals("") && !(v2.equals(""))) {
            var3.setText(v2);
            var2.setText("");
        }
    }

    private void runMD4() {
        String v1 = var1.getText();
        String v2 = var2.getText();
        if (v2.equals("") && !(v1.equals(""))) {
            var2.setText(v1);
            var1.setText("");
        }
    }

    private void run7() {
        Thread th = new Thread() {
            @Override
            public void run() {
                try {
                    for (int a = 0; a <= 7; a++) {
                        Thread.sleep(800);
                        if (a == 1) {
                            run7a();
                        }
                        if (a == 2) {
                            run7b();
                            checkHead();
                        }
                        if (a == 3) {
                            run7c();
                        }
                        if (a == 4) {
                            run7d();
                        }
                        if (a == 5) {
                            checkMD1();
                        }
                    }
                } catch (Exception ex) {
                    System.out.println(ex);
                }
            }
        };
        th.start();

    }

    private void run7a() {
        String data = var5.getText();
        var6.setText(data);
        var5.setText("");
    }

    private void run7b() {
        String data = var6.getText();
        var7.setText(data);
        var6.setText("");
    }

    private void run7c() {
        String data = var7.getText();
        var7.setText("");
        var8.setText(data);

    }

    private void run7d() {
        String data = var7.getText();
        var7.setText(data);
        var8.setText(data);
    }

    public void resetColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(255, 255, 255));
    }

    public void setColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(44, 62, 80));
    }

    public void setBorder2(JPanel panel) {
        panel.setBorder(new LineBorder(new java.awt.Color(44, 62, 80)));
    }

    public void resetBorder(JPanel panel) {
        panel.setBorder(BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }

    public void setColorTF(JLabel label) {
        label.setForeground(new java.awt.Color(255, 255, 225));
    }

    public void resetColorTF(JLabel label) {
        label.setForeground(new java.awt.Color(44, 62, 80));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Queue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Queue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Queue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Queue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Queue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TF1;
    private javax.swing.JLabel TF2;
    private javax.swing.JLabel back;
    private javax.swing.JPanel dequeue;
    private javax.swing.JPanel enqueue;
    private javax.swing.JLabel head1;
    private javax.swing.JLabel head2;
    private javax.swing.JLabel head3;
    private javax.swing.JTextField inputX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel jlStack;
    private javax.swing.JLabel notes;
    private javax.swing.JLabel tail1;
    private javax.swing.JLabel tail2;
    private javax.swing.JLabel tail3;
    private javax.swing.JLabel tail4;
    private javax.swing.JTextField var1;
    private javax.swing.JTextField var2;
    private javax.swing.JTextField var3;
    private javax.swing.JTextField var4;
    private javax.swing.JTextField var5;
    private javax.swing.JTextField var6;
    private javax.swing.JTextField var7;
    private javax.swing.JTextField var8;
    private javax.swing.JTextField varx;
    private javax.swing.JTextField vary;
    // End of variables declaration//GEN-END:variables
}
