/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas_prakstrukdat;

import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;

/**
 *
 * @author SUCI WULANDARI - 210605110154
 */
public class Sorting extends javax.swing.JFrame {

    /**
     * Creates new form Sorting
     */
    public Sorting() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        insert = new javax.swing.JPanel();
        nInsert = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bubble = new javax.swing.JPanel();
        nBubble = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));
        jPanel1.setPreferredSize(new java.awt.Dimension(1010, 520));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray));
        jPanel2.setPreferredSize(new java.awt.Dimension(734, 437));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insert.setBackground(new java.awt.Color(255, 255, 255));
        insert.setPreferredSize(new java.awt.Dimension(120, 120));
        insert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                insertMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                insertMouseExited(evt);
            }
        });
        insert.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nInsert.setFont(new java.awt.Font("HP Simplified Hans", 0, 24)); // NOI18N
        nInsert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nInsert.setText("Insert");
        insert.add(nInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 50));

        jPanel2.add(insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 160, 150));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 65)); // NOI18N
        jLabel6.setText("SORTING");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        bubble.setBackground(new java.awt.Color(255, 255, 255));
        bubble.setPreferredSize(new java.awt.Dimension(120, 120));
        bubble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bubbleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bubbleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bubbleMouseExited(evt);
            }
        });
        bubble.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nBubble.setFont(new java.awt.Font("HP Simplified Hans", 0, 24)); // NOI18N
        nBubble.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nBubble.setText("Bubble");
        bubble.add(nBubble, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jPanel2.add(bubble, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 160, 150));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 23, 960, 470));

        Exit.setFont(new java.awt.Font("Leelawadee", 1, 20)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setText("X ");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, -10, 40, 40));

        back.setFont(new java.awt.Font("Leelawadee", 1, 20)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("<");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        doexit();
    }//GEN-LAST:event_ExitMouseClicked
    public void doexit() {
        int confirm = JOptionPane.showConfirmDialog(null,
                "Apa Anda Akan Keluar?", "Tutup Aplikasi",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);

        }
    }
    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:

        new First().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backMouseClicked

    private void bubbleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bubbleMouseClicked
        // TODO add your handling code here:
        new bubble().setVisible(true); // kembali ke frame Bubble
        this.setVisible(false); // untuk menutup page/frame sebelumnyaa
    }//GEN-LAST:event_bubbleMouseClicked

    private void insertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertMouseClicked
        // TODO add your handling code here:
        new insert().setVisible(true); // kembali ke frame Merge Sort
        this.setVisible(false); // untuk menutup page/frame sebelumnyaa
    }//GEN-LAST:event_insertMouseClicked

    private void bubbleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bubbleMouseEntered
        // TODO add your handling code here:
        x1();
    }//GEN-LAST:event_bubbleMouseEntered
    public void x1() {
        setBorder2(bubble);
        setColor(bubble);
        setColorTombol(nBubble);
    }
    private void bubbleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bubbleMouseExited
        // TODO add your handling code here:
        y1();
    }//GEN-LAST:event_bubbleMouseExited
    public void y1() {
        resetColorTombol(nBubble);
        resetColor(bubble);
    }
    private void insertMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertMouseEntered
        // TODO add your handling code here:
        x4();
    }//GEN-LAST:event_insertMouseEntered
    public void x4() {
        setBorder2(insert);
        setColor(insert);
        setColorTombol(nInsert);
    }
    private void insertMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertMouseExited
        // TODO add your handling code here:
        y4();
    }//GEN-LAST:event_insertMouseExited
    public void y4() {
        resetColorTombol(nInsert);
        resetColor(insert);
    }

    public void resetColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(255, 255, 255));
    }

    public void setColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(44, 62, 80));
    }

    public void setColorTombol(JLabel label) {
        label.setForeground(new java.awt.Color(255, 255, 225));
    }

    public void resetColorTombol(JLabel label) {
        label.setForeground(new java.awt.Color(44, 62, 80));
    }

    public void setBorder2(JPanel panel) {
        panel.setBorder(new LineBorder(new java.awt.Color(44, 62, 80)));
    }

    public void resetBorder(JPanel panel) {
        panel.setBorder(BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sorting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sorting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sorting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sorting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sorting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel back;
    private javax.swing.JPanel bubble;
    private javax.swing.JPanel insert;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nBubble;
    private javax.swing.JLabel nInsert;
    // End of variables declaration//GEN-END:variables
}
