/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas_prakstrukdat;

import javax.swing.BorderFactory; // untuk border pd panel yg berubah itu 
import javax.swing.JLabel;
import javax.swing.JOptionPane; // jendela dialog
import javax.swing.JPanel;
import javax.swing.border.LineBorder; //line border
import java.io.*;
import java.util.*;

/**
 *
 * @author SUCI WULANDARI - 210605110154
 */
public class Stack extends javax.swing.JFrame {

    algoritm theStack; //nyambungin ke kelas alg

    public Stack() {
        initComponents();
        inputX.setText("");
        varx.setText("");
        vary.setText("");
        var1.setText("");
        var2.setText("");
        var3.setText("");
        var3.setText("");
        var4.setText("");
        var5.setText("");
        note.setVisible(false);

        theStack = new algoritm(5);

        setLocationRelativeTo(this);// Frameketengah
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        page = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inputX = new javax.swing.JTextField();
        p0 = new javax.swing.JPanel();
        TF1 = new javax.swing.JLabel();
        pop = new javax.swing.JPanel();
        TF2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        check = new javax.swing.JPanel();
        TF3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        var1 = new javax.swing.JTextField();
        var2 = new javax.swing.JTextField();
        var3 = new javax.swing.JTextField();
        var4 = new javax.swing.JTextField();
        var5 = new javax.swing.JTextField();
        varx = new javax.swing.JTextField();
        vary = new javax.swing.JTextField();
        note = new javax.swing.JLabel();
        ar = new javax.swing.JLabel();
        peek = new javax.swing.JLabel();
        jlStack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));
        jPanel1.setPreferredSize(new java.awt.Dimension(1010, 520));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setFont(new java.awt.Font("Leelawadee", 1, 20)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("<");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, -1));

        Exit.setFont(new java.awt.Font("Leelawadee", 1, 20)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setText("X ");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, -10, 40, 40));

        page.setBackground(new java.awt.Color(0, 102, 102));
        page.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray));
        page.setPreferredSize(new java.awt.Dimension(734, 437));
        page.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 60)); // NOI18N
        jLabel1.setText("STACK");
        page.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 190, 90));

        inputX.setBackground(new java.awt.Color(0, 102, 102));
        inputX.setFont(new java.awt.Font("HP Simplified Hans", 0, 18)); // NOI18N
        inputX.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputX.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 62, 80), 1, true), "Data", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        page.add(inputX, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 130, 60));

        p0.setBackground(new java.awt.Color(255, 255, 255));
        p0.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 62, 80), 1, true)));
        p0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p0MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p0MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p0MouseExited(evt);
            }
        });
        p0.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TF1.setBackground(new java.awt.Color(255, 255, 255));
        TF1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        TF1.setText("PUSH");
        TF1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TF1MouseEntered(evt);
            }
        });
        p0.add(TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 60, 30));

        page.add(p0, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 130, 50));

        pop.setBackground(new java.awt.Color(255, 255, 255));
        pop.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                popMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                popMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                popMouseExited(evt);
            }
        });
        pop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TF2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        TF2.setText("POP");
        pop.add(TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 40, 30));

        page.add(pop, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 130, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Array :");
        page.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 82, 38));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Peek :");
        page.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 80, 24));

        check.setBackground(new java.awt.Color(255, 255, 255));
        check.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                checkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                checkMouseExited(evt);
            }
        });
        check.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TF3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        TF3.setText("CHECK");
        check.add(TF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 60, 30));

        page.add(check, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 130, 50));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        page.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, -1, 233));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        page.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, 50, 233));
        page.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 70, 20));
        page.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, 70, 20));
        page.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 280, 70, 20));
        page.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, 70, 20));

        var1.setBackground(new java.awt.Color(0, 102, 102));
        var1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        var1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        var1.setText("var 1");
        var1.setBorder(null);
        var1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var1ActionPerformed(evt);
            }
        });
        page.add(var1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, 60, 40));

        var2.setBackground(new java.awt.Color(0, 102, 102));
        var2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        var2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        var2.setText("var 2");
        var2.setBorder(null);
        page.add(var2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 70, 50));

        var3.setBackground(new java.awt.Color(0, 102, 102));
        var3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        var3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        var3.setText("var 3");
        var3.setBorder(null);
        page.add(var3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, 50, 40));

        var4.setBackground(new java.awt.Color(0, 102, 102));
        var4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        var4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        var4.setText("var 4");
        var4.setBorder(null);
        page.add(var4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 50, 40));

        var5.setBackground(new java.awt.Color(0, 102, 102));
        var5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        var5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        var5.setText("var 5");
        var5.setBorder(null);
        page.add(var5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, 60, 30));

        varx.setBackground(new java.awt.Color(0, 102, 102));
        varx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        varx.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        varx.setText("var x");
        varx.setBorder(null);
        page.add(varx, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 60, 40));

        vary.setBackground(new java.awt.Color(0, 102, 102));
        vary.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vary.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vary.setText("var y");
        vary.setBorder(null);
        page.add(vary, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 60, 40));

        note.setFont(new java.awt.Font("HP Simplified Hans", 0, 18)); // NOI18N
        note.setText("Full");
        page.add(note, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 180, 50, 30));

        ar.setFont(new java.awt.Font("HP Simplified Hans", 0, 18)); // NOI18N
        ar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ar.setText("-");
        page.add(ar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 140, 60));

        peek.setFont(new java.awt.Font("HP Simplified Hans", 0, 18)); // NOI18N
        peek.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        peek.setText("-");
        page.add(peek, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 140, 60));

        jlStack.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlStack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlStack.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Progress", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N
        page.add(jlStack, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 220, 250));

        jPanel1.add(page, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 960, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here
        new First().setVisible(true);
        this.setVisible(false); //frame ke X
    }//GEN-LAST:event_backMouseClicked

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        doexit();
    }//GEN-LAST:event_ExitMouseClicked
    public void doexit() {
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin keluar?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0); //untuk keluar dari program.
        }
    }

    private void TF1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_TF1MouseEntered

    private void p0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p0MouseClicked
        // TODO add your handling code here:

        theStack.push(inputX.getText()); //manggil methof push dan memasukkan inputX
        jlStack.setText(Arrays.toString(theStack.stackArray)); //set jlStack array yang dikonvert dari array data
     
        String data = inputX.getText();

        if (data.equals("")) {
            JOptionPane.showMessageDialog(null, "Masukkan Data!");

        } else {
            Thread th = new Thread() { // ini kelas pd java untuk mengset waktu eksekusi
                @Override
                public void run() {
                    try {
                        for (int a = 0; a <= 10; a++) { // ini itu buat var yang tiap kotak
                            Thread.sleep(500); // mengSet Waktu pending selama 5 milidetik
                            if (a == 1) {
                                run1();
                            }
                            if (a == 2) {
                                run2();
                            }
                            if (a == 3) {
                                run3();
                            }
                            if (a == 4) {
                                run4();
                            }
                            if (a == 5) {
                                run5();
                            }
                            if (a == 6) {
                                run6();
                            }
                        }
                    } catch (Exception ex) {
                        System.out.println(ex);
                    }
                }
            };
            th.start(); //thread start

        }
    }//GEN-LAST:event_p0MouseClicked

    private void run1() {
        String data = varx.getText();
        String input = inputX.getText();

        if (data.equals("")) {

            varx.setText(input);
        }

    }

    private void run2() {
        String data = var1.getText();
        String input = varx.getText();

        if (data.equals("")) {

            var1.setText(input);
            varx.setText("");
        }

    }

    private void run3() {
        String data = var2.getText();
        String a1 = var1.getText();

        if (data.equals("")) {
            var2.setText(a1);
            var1.setText("");
        } else {
            vary.setText(a1);
            var1.setText("");
            note.setVisible(true);
        }
    }

    private void run4() {
        String data = var3.getText();
        String a12 = var2.getText();

        if (data.equals("")) {
            var3.setText(a12);
            var2.setText("");
        }
    }

    private void run5() {
        String data = var4.getText();
        String a13 = var3.getText();

        if (data.equals("")) {
            var4.setText(a13);
            var3.setText("");
        }
    }

    private void run6() {
        String data = var5.getText();
        String a14 = var4.getText();

        if (data.equals("")) {
            var5.setText(a14);
            var4.setText("");
        }
    }

// method run 7-10 itu untuk pop
    private void run7() { // ketika pop data yang ada di var2
        Thread th = new Thread() {
            @Override
            public void run() {
                try {
                    for (int a = 0; a <= 10; a++) {
                        Thread.sleep(500);
                        if (a == 1) {
                            run7a();
                        }
                        if (a == 2) {
                            run7b();
                        }
                        if (a == 3) {
                            run7c();
                        }
                    }
                } catch (Exception ex) {
                    System.out.println(ex);
                }
            }
        };
        th.start();

    }

    private void run7a() {

        String a2 = var2.getText();

        var1.setText(a2);
        var2.setText("");

    }

    private void run7b() {

        String data = var1.getText();
        vary.setText(data);
        var1.setText("");

    }

    private void run7c() {

        String data = var1.getText();
        vary.setText("");

    }

    private void run8() { // ketika pop data yang ada di var3
        Thread th = new Thread() {
            @Override
            public void run() {
                try {
                    for (int a = 0; a <= 10; a++) {
                        Thread.sleep(500);
                        if (a == 1) {
                            run8a();
                        }
                        if (a == 2) {
                            run8b();
                        }
                        if (a == 3) {
                            run8c();
                        }
                        if (a == 4) {
                            run8d();
                        }
                    }
                } catch (Exception ex) {
                    System.out.println(ex);
                }
            }
        };
        th.start();

    }

    private void run8a() {

        String a2 = var3.getText();
        var2.setText(a2);
        var3.setText("");

    }

    private void run8b() {

        String data = var2.getText();
        var1.setText(data);
        var2.setText("");

    }

    private void run8c() {

        String data = var1.getText();
        vary.setText(data);
        var1.setText("");

    }

    private void run8d() {
        vary.setText("");

    }

    private void run9() { // ketika pop data yang ada di var4
        Thread th = new Thread() {
            @Override
            public void run() {
                try {
                    for (int a = 0; a <= 10; a++) {
                        Thread.sleep(500);
                        if (a == 1) {
                            run9a();
                        }
                        if (a == 2) {
                            run9b();
                        }
                        if (a == 3) {
                            run9c();
                        }
                        if (a == 4) {
                            run9d();
                        }
                        if (a == 5) {
                            run9e();
                        }
                    }
                } catch (Exception ex) {
                    System.out.println(ex);
                }
            }
        };
        th.start();

    }

    private void run9a() {

        String a2 = var4.getText();
        var3.setText(a2);
        var4.setText("");

    }

    private void run9b() {

        String data = var3.getText();
        var2.setText(data);
        var3.setText("");

    }

    private void run9c() {

        String data = var2.getText();
        var1.setText(data);
        var2.setText("");

    }

    private void run9d() {

        String data = var1.getText();
        vary.setText(data);
        var1.setText("");

    }

    private void run9e() {
        vary.setText("");

    }

    private void run10() {// ketika pop data yang ada di var5
        Thread th = new Thread() {
            @Override
            public void run() {
                try {
                    for (int a = 0; a <= 10; a++) {
                        Thread.sleep(500);
                        if (a == 1) {
                            run10a();
                        }
                        if (a == 2) {
                            run10b();
                        }
                        if (a == 3) {
                            run10c();
                        }
                        if (a == 4) {
                            run10d();
                        }
                        if (a == 5) {
                            run10e();
                        }
                        if (a == 6) {
                            run10f();
                        }
                    }
                } catch (Exception ex) {
                    System.out.println(ex);
                }
            }
        };
        th.start();

    }

    private void run10a() {

        String a2 = var5.getText();
        var4.setText(a2);
        var5.setText("");

    }

    private void run10b() {

        String data = var4.getText();
        var3.setText(data);
        var4.setText("");

    }

    private void run10c() {

        String data = var3.getText();
        var2.setText(data);
        var3.setText("");

    }

    private void run10d() {

        String data = var2.getText();
        var1.setText(data);
        var2.setText("");

    }

    private void run10e() {

        String data = var1.getText();
        vary.setText(data);
        var1.setText("");

    }

    private void run10f() {
        vary.setText("");
    }

    private void p0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p0MouseEntered
        // TODO add your handling code here:
        x1();
    }//GEN-LAST:event_p0MouseEntered
    public void x1() {
        setColor(p0);
        setColorTF(TF1);
        setBorder2(p0);
    }

    private void p0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p0MouseExited
        // TODO add your handling code here
        y1();
    }//GEN-LAST:event_p0MouseExited
    public void y1() {
        resetColor(p0);
        resetColorTF(TF1);
    }

    private void popMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popMouseClicked
        // TODO add your handling code here:

        theStack.pop();
        jlStack.setText(Arrays.toString(theStack.stackArray));

        String b = var1.getText();
        String c = var2.getText();
        String d = var3.getText();
        String e = var4.getText();
        String f = var5.getText();

//method equals() itu untuk membandingkan 2 variabel
        if (b.equals("") && !(c.equals(""))) {
            run7();
            note.setVisible(false); // ketika pop biar note "Full" itu False
            vary.setText("");
        } else if (c.equals("") && !d.equals("")) {
            run8();
            note.setVisible(false);
            vary.setText("");
        } else if (d.equals("") && !e.equals("")) {
            run9();
            note.setVisible(false);
            vary.setText("");
        } else if (e.equals("") && !f.equals("")) {
            run10();
            note.setVisible(false);
            vary.setText("");
        }
    }//GEN-LAST:event_popMouseClicked

    private void popMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popMouseEntered
        // TODO add your handling code here:
        x2();
    }//GEN-LAST:event_popMouseEntered
    public void x2() {
        setBorder2(pop);
        setColor(pop);
        setColorTF(TF2);
    }

    private void popMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popMouseExited
        // TODO add your handling code here:
        y2();
    }//GEN-LAST:event_popMouseExited
    public void y2() {
        resetColorTF(TF2);
        resetColor(pop);
    }

    private void checkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkMouseClicked
        // TODO add your handling code here:
        String b = var1.getText();
        String c = var2.getText();
        String d = var3.getText();
        String e = var4.getText();
        String f = var5.getText();

//method equals() itu untuk membandingkan 2 variabel
        if (b.equals("") && !(c.equals(""))) {
            ar.setText("{ " + f + " - " + e + " - " + d + " - " + c + " }");
            peek.setText(c);
        } else if (c.equals("") && !d.equals("")) {
            ar.setText("{ " + f + " - " + e + " - " + d + " }");
            peek.setText(d);
        } else if (d.equals("") && !e.equals("")) {
            ar.setText("{ " + f + " - " + e + " }");
            peek.setText(e);
        } else if (e.equals("") && !f.equals("")) {
            ar.setText("{ " + f + " }");
            peek.setText(f);
        } else if (f.equals("")) {
            ar.setText("{ Kosong }");
            peek.setText("{ Kosong }");
        }
    }//GEN-LAST:event_checkMouseClicked

    private void checkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkMouseEntered
        // TODO add your handling code here:
        x3();
    }//GEN-LAST:event_checkMouseEntered
    public void x3() {
        setColor(check);
        setBorder2(check);
        setColorTF(TF3);
    }

    private void checkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkMouseExited
        // TODO add your handling code here:
        y3();
    }//GEN-LAST:event_checkMouseExited

    private void var1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_var1ActionPerformed
    public void y3() {
        resetColorTF(TF3);
        resetColor(check);
    }

    public void resetColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(255, 255, 255));
    }

    public void setColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(44, 62, 80));
    }

    public void setBorder2(JPanel panel) {
        panel.setBorder(new LineBorder(new java.awt.Color(44, 62, 80)));
    }

    public void resetBorder(JPanel panel) {
        panel.setBorder(BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }

    public void setColorTF(JLabel label) {
        label.setForeground(new java.awt.Color(255, 255, 225));
    }

    public void resetColorTF(JLabel label) {
        label.setForeground(new java.awt.Color(44, 62, 80));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel TF1;
    private javax.swing.JLabel TF2;
    private javax.swing.JLabel TF3;
    private javax.swing.JLabel ar;
    private javax.swing.JLabel back;
    private javax.swing.JPanel check;
    private javax.swing.JTextField inputX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel jlStack;
    private javax.swing.JLabel note;
    private javax.swing.JPanel p0;
    private javax.swing.JPanel page;
    private javax.swing.JLabel peek;
    private javax.swing.JPanel pop;
    private javax.swing.JTextField var1;
    private javax.swing.JTextField var2;
    private javax.swing.JTextField var3;
    private javax.swing.JTextField var4;
    private javax.swing.JTextField var5;
    private javax.swing.JTextField varx;
    private javax.swing.JTextField vary;
    // End of variables declaration//GEN-END:variables
}
